### ISSUE TITLE
Select Drop Downlist & Foreign key lookups

### ISSUE THREAD

**Issue by weedkiller** [ardalis/SmartEnum#10]
Hi, nice lib, can you tell me how to get a select list, 1)  `EnumToSelectDropDownList()`

A function to populate dropdowns 
```
public IEnumerable<SelectListItem> Creating_a_select_list(State selected)
{
    return State.GetAll().Select(
        x => new SelectListItem
        {
            Selected = x == selected,
            Text = x.Description,
            Value = x.Value.ToString()
        });
}
```
and 2) reverse lookup [EF foreign-key fields in DB like here... ](https://github.com/timabell/ef-enum-to-lookup)
```
var enumToLookup = new EnumToLookup();
enumToLookup.NameFieldLength = 42; // optional, example of how to override default values
enumToLookup.Apply(context);

```

**Comment by ardalis** [comment]
Sorry, haven't had time to run with this one. I'm guessing if you made this a question on StackOverflow.com you'd have an answer within a day or two (and perhaps you could link to it from here). Thanks!
