### ISSUE TITLE
Version 2.01 issue

### ISSUE THREAD

**Issue by ghendo** [ardalis/SmartEnum#113]
On update to this version I get error
FileLoadException: Could not load file or assembly 'Ardalis.SmartEnum, Version=1.0.11.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by ardalis** [comment]
Thanks, let me see if I can repro this. In the meantime hopefully you can keep using a previous version?

**Comment by ghendo** [comment]
Yes previous version is  fine

**Comment by tomasgerhardsen** [comment]
I'm getting the same error. I'm also using the Ardalis.SmartEnum.JsonNet package if that could help pinpoint the problem.

**Comment by jake-carpenter** [comment]
I'm getting this error as well after adding `Ardalis.SmartEnum.SystemTextJson` 1.0.0 which requires `Ardalis.SmartEnum` >= 1.0.11. Apparently it's not happy with 2.0.1.

**Comment by BenWhite27** [comment]
Same, added reference to SystemTextJson and now the aspnetcore project is hating me.

**Comment by kjbetz** [comment]
I'm also having this same issue. I assume because tried using JsonNet or SystemTextJson packages. Looks like above pull request fixes issue. For now, I changed to version 1.0.11.

**Comment by af4jm** [comment]
I'm seeing this in a brand new .NET 5 Azure Functions project ... work-around is to remove the reference to Ardalis.SmartEnum, letting Ardalis.SmartEnum.Json bring along the version it wants

**Comment by ardalis** [comment]
Hopefully this is fixed now in v2.1.0.

Can someone please confirm? Closing for now but reopen if the issue remains.

**Comment by kjbetz** [comment]
I've updated all versions of my `SmartEnum` packages and am not seeing any errors.

Thanks!
