### ISSUE TITLE
Why not add to list within constructor?

### ISSUE THREAD

**Issue by Andrew-Hanlon** [ardalis/SmartEnum#12]
Curious: Why was the type-member approach chosen over the simpler and more common approach of adding to the list during construction? This seems well researched, so I may be missing something, but the only benefit I can see is the ability to provide lazy initialization of the list; however this seems like a debatable optimization since any advanced usage (the reason for the approach) requires instantiation. It also would seem to have downsides, like relying on the implementer following a convention (fields vs properties, etc.). Thanks!

**Comment by ardalis** [comment]
Are you wondering why this code:

```
        private static readonly Lazy<List<TEnum>> _list = new Lazy<List<TEnum>>(ListAllOptions);

        private static List<TEnum> ListAllOptions()
        {
            Type t = typeof(TEnum);
            return t.GetFields(BindingFlags.Public | BindingFlags.Static)
            .Where(p => t.IsAssignableFrom(p.FieldType))
            .Select(pi => (TEnum)pi.GetValue(null))
            .OrderBy(p => p.Name)
            .ToList();
        }
```
isn't in the constructor, instead? I believe we started out using that approach but had to shift to this one because the reflection code doesn't work when `TEnum` hasn't yet been constructed.

**Comment by Andrew-Hanlon** [comment]
Not quite - I'm wondering why use reflection at all, versus just using:

```````
private static readonly List<TEnum> _list = new List<TEnum>();

protected EnumBase(string name, TValue value)
 {
    Name = name;
    Value = value;
    _list.Add((TEnum)this);
}
```````
This will build the list during static initialization.

**Comment by ardalis** [comment]
Started with that:
https://github.com/ardalis/SmartEnum/commit/abb5f180ebfb577ba2d4d3a8e1b67f8de5368136

Ran into this:
https://github.com/ardalis/SmartEnum/issues/2

**Comment by Andrew-Hanlon** [comment]
I *believe* that can be fixed simply by including a static constructor:

ECMA-334:

> 17.4.5.1: "If a static constructor (§17.11) exists in the class, execution of the static field initializers occurs immediately prior to executing that static constructor. Otherwise, the static field initializers are executed at an implementation-dependent time prior to the first use of a static field of that class."
> 
And:
> 
> 17.11: The execution of a static constructor is triggered by the first of the following events to occur within an application domain:
> 
> An instance of the class is created.
> Any of the static members of the class are referenced.
> If a class contains the Main method (§10.1) in which execution begins, the static constructor for that class executes before the Main method is called. If a class contains any static fields with initializers, those initializers are executed in textual order immediately prior to executing the static constructor (§17.4.5).

**Comment by Andrew-Hanlon** [comment]
Ah, I see what I was missing: The *derived* static initialization is not triggered. 

A decent workaround, without having reflection on the members is to add a static constructor on the base class that calls the derived static constructor like:

````
static SmartEnum() =>
System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(typeof(TEnum).TypeHandle);
````

This would guarantee derived initialization.

**Comment by ardalis** [comment]
Do you have time to put that into a PR I could review?

**Comment by yarrgh** [comment]
I've attempted to implement this but am getting interesting test results.

Source code is here:
https://gist.github.com/yarrgh/fb1d15c448aee01c96b8cfa764d87553

When running all unit tests together,  `SmartEnumList.ReturnsAllDefinedSmartEnums()` fails more often than it succeeds. (All other tests succeed)

This is the response:
```
SmartEnum.UnitTests.SmartEnumList.ReturnsAllDefinedSmartEnums

Assert.Equal() Failure
Expected: 3
Actual:   0
   at SmartEnum.UnitTests.SmartEnumList.ReturnsAllDefinedSmartEnums() in C:\projects\SmartEnum\src\SmartEnum.UnitTests\SmartEnumList.cs:line 12
```
It will randomly succeed when ran with all of the unit tests. However, it always succeeds when ran alone.

Any idea why this may be happening?

**Comment by ardalis** [comment]
By default xUnit will run tests in parallel. This sounds like race condition in which some test is hitting the static constructor before another test (or they're hitting it at the same time). You might be able to address the issue with a lock statement in the static constructor. Another "fix" would be to configure the tests to only run sequentially, which you can do using a TestCollection (https://xunit.github.io/docs/running-tests-in-parallel.html). However, this may just mask the problem, which could still occur in production in multi-threaded environments.

**Comment by Andrew-Hanlon** [comment]
@ardalis C#'s staric constructors are guaranteed thread safe, so I don't believe that can be the cause. Are the tests using fields or properties for the enum members?

**Comment by ardalis** [comment]
@Andrew-Hanlon Thanks. Yeah, I didn't think I'd ever heard of needing a lock inside a static constructor, so good to confirm that shouldn't be the issue.  The tests mostly go against this enum:

https://github.com/ardalis/SmartEnum/blob/master/src/SmartEnum.UnitTests/TestEnum.cs

which calls into SmartEnum's constructor and sets its `Name` and `Value` properties.

**Comment by ardalis** [comment]
I'm closing this out unless there's more that needs to happen. Let me know, @Andrew-Hanlon .
