### ISSUE TITLE
SmartEnum Not Working with Entity Framework

### ISSUE THREAD

**Issue by mikaelsnavy** [ardalis/SmartEnum#15]
Hello!

I am having an issue with SmartEnum and a class I'm trying to use EF Code First migrations with. My SmartEnum looks like this:

```
    public class DateTimeAccuracy : SmartEnum<DateTimeAccuracy, int>
    {
        public static DateTimeAccuracy DateTime = new DateTimeAccuracy(nameof(DateTime), 0);
        public static DateTimeAccuracy Date = new DateTimeAccuracy(nameof(Date), 1);
        etc...

        protected DateTimeAccuracy(string Name, int Value) : base(Name, Value)
        {
        }
    }
```
I'm using EF Core (2.1) and when attempting to add a migration, I get the following error:
`System.InvalidOperationException: No suitable constructor found for entity type 'DateTimeAccuracy'. The following parameters could not be bound to properties of the entity: 'Name', 'Value'.`

Ahhhh! There is no parameterless constructor for EF to work with! Looking at [this page](https://ardalis.com/persisting-the-type-safe-enum-pattern-with-ef-6), I just need a blank constructor to make EF happy. I don't believe the SmartEnum library supports it "as is" but please correct me if I'm wrong. :smile: 

If it's not compatible, I believe I have a solution. If needed, should I do a pull request to master or bugfix1?
[see here for my fix](https://github.com/mikaelsnavy/SmartEnum/commit/273b55eb760a9a5b9eff51b19e66858a68e9fddc)

Thanks!
Mikael

**Comment by yarrgh** [comment]
See https://github.com/ardalis/SmartEnum/issues/13#issuecomment-380977458 for how to use with entity framework.

**Comment by mikaelsnavy** [comment]
Fix accepted as a pull request! :+1:
