### ISSUE TITLE
License element not found when creating SBOM

### ISSUE THREAD

**Issue by lmingle** [ardalis/SmartEnum#176]
I've included SmartEnum NuGet package in a solution I'm working on.

I attempted to create a Software Bill of Materials (SBOM) using the CycloneDX module for .NET (https://github.com/CycloneDX/cyclonedx-dotnet) to automate the SBOM generation. In the resulting XML, all of the NuGet projects included the license tag except for SmartEnum.

Please look into what changes are needed to have the license appear in the SBOM generated by CycloneDX.

**Comment by coderpatros** [comment]
Adding `<PackageLicenseExpression>MIT</PackageLicenseExpression>` to `Directory.Build.props` or the project files should do it. That will then be included in the NuGet package metadata.

**Comment by ardalis** [comment]
Will be in next release after 2.1.0

**Comment by lmingle** [comment]
The NuGet package doesn't seem to have the license information show up on [NuGet](https://www.nuget.org/packages/Ardalis.SmartEnum/) or [NuGet Package Explorer](https://nuget.info/packages/UnitsNet/4.128.0)](https://nuget.info/packages/Ardalis.SmartEnum/2.1.0).
I compared several other projects (QuestPDF, UnitsNet & HelixToolkit) which are showing the license and see either `<PackageLicenseExpression>MIT</PackageLicenseExpression>` or `<PackageLicenseUrl>https://opensource.org/licenses/MIT</PackageLicenseUrl>` in the .csproj file.

I checked some of your other projects on NuGet and see the same for those packages. [GuardClauses](https://www.nuget.org/packages/Ardalis.GuardClauses/)

The [Ardalis.ApiEndpoints](https://www.nuget.org/packages/Ardalis.ApiEndpoints/) does show the license as `LICENSE.txt` (same casing) and that project file has `<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>`.
