### ISSUE TITLE
Not a real issue

### ISSUE THREAD

**Issue by os1r1s110** [ardalis/SmartEnum#19]
As the title says, it's not a real issue but more of a question.

I'd like to know why the decision was made to put the "name" property before the "value" in the constructor. Most of the time when working with key-value pairs or enums, it is logical to put the key first IMO and I'd like to know if there's any reason why it was made differently.

Thanks in advance!

**Comment by yarrgh** [comment]
The name is the key. The value is, well, the value.

It does follow the convention of dealing with the key-value pairs

**Comment by os1r1s110** [comment]
Isn't it inefficient to use a string as key?

And I personally find it counter-intuitive to think about the "name" as the variable supposed to hold my "key" and the "value" holding the display name or other info... 

In that case, I should create a SelectList using the "name" as value and "value" as the text field... 

Also, on the way back, I should use a string as the type to bind the result to... To me it doesn't seem logical at all, but that's my own opinion. 

Thanks for your input though.. I'l try to wrap my head around the inconsistency (IMO) :)

**Comment by ardalis** [comment]
For a SelectList you want to display the Name but use the Value as the SelectList’s Value, right? I’m not seeing the inconsistency. Can you demonstrate with a bit of code perhaps?

**Comment by os1r1s110** [comment]
You are totally right and I never said otherwise (sorry if I was unclear about that).

The only thing that bothered me in the beginning (as mentioned in the first post) was the initialization in which the "value", which is equivalent to the key, was put after the name. I would have liked to align the keys/values at the beginning as shown below to be able to see quickly the keys used, but that's a really minor thing ahah.

I guess I read it at first as if the first param was indeed treated as the enum's equivalent key, but it's not, it's the enum's equivalent "textual" value, which is totally fine, and the value is treated the same as the underlying type, which is effectively an int in most cases. To be totally honest now that I look back at it, I wonder why I thought it was inconsistent lol -_- I guess I was half awake. Sorry for bothering :)

```
public class TestEnumClass : SmartEnum<TestEnumClass, int>
{
    public static readonly TestEnumClass FirstKey  = new TestEnumClass(0, "Display name for first key");
    public static readonly TestEnumClass SecondKey = new TestEnumClass(1, "Name for second item");
    public static readonly TestEnumClass ThirdKey  = new TestEnumClass(2, "etc...");
    private TestEnumClass(string name, int value) : base(name, value){}
}
```

**Comment by yarrgh** [comment]
Yes, the name is just a textual representation of the key. The key is actually the static field in the class (`TestEnumClass.FirstKey`). The name is supposed to represent that name or be meaningful in some way. Usually it is some variant of the variable name. This is why the README uses `nameof()` so that if the variable is renamed, the textual "key" remains the same as the variable name.

The name can be whatever you want it to be. If you're going to use it for a list and want to store the displayed message in the SmartEnum, I'd suggest extending SmartEnum and adding a description property so that you can use it in a list.

```c#
public TestEnumClass : SmartEnum<TestEnumClass, int>
{
    public static readonly TestEnumClass FirstKey  = new TestEnumClass(nameof(FirstKey), 0, "Display name for first key");
    public static readonly TestEnumClass SecondKey = new TestEnumClass(nameof(SecondKey), 1, "Name for second item");
    public static readonly TestEnumClass ThirdKey  = new TestEnumClass(nameof(ThirdKey), 2, "etc...");

    public string Description { get; }

    public TestEnumClass(string name, int value, string description) : base (name, value) {
        Descriptions = description;
    }
}
```

**Comment by os1r1s110** [comment]
That's exactly what I did :)

**Comment by os1r1s110** [comment]
Would it be useful to add a default implementation in the SmartEnum class that would get the SelectList from the value and name of the generated list directly?

**Comment by ardalis** [comment]
I wouldn't add an implementation in the SmartEnum class that was tied to SelectList or any other UI element. I could see adding either samples showing how to use SmartEnum with a SelectList or even including some extension methods that would create a SelectList from a SmartEnum or something like that. Would that help?

**Comment by os1r1s110** [comment]
Oh I'm totally fine using it as is. I was just wondering if it would be
useful to add such extension methods to make it less verbose when
generating a select list with the default name/value properties
