### ISSUE TITLE
Equals implementation

### ISSUE THREAD

**Issue by DeveTho** [ardalis/SmartEnum#20]
I was wondering if it would make sense to override and implement `Equals()` for the `SmartEnum`. Because now, if I'm checking for equality, I'm doing something like `TestEnum.One.Value == myEnumVar.Value`, which is not only a little more tedious, but you can also make mistakes.

If the answer is positive, I could try to do this myself and send a PR your way, if you like. :) In that case, I would have one question about what would be "the right way": two `SmartEnum` instances would be considered equal if their `Name` property is equal, right (and not necessarily their `Value` property, as in my example)?

Thanks by the way for providing this! I really like to use it. :)

**Comment by yarrgh** [comment]
Something like `TestEnum.One == myEnumVar`? 

Sounds like a great idea to me.

**Comment by ardalis** [comment]
I’d definitely consider a PR with this, thanks!

**Comment by DeveTho** [comment]
Cool! I'll have a look at it somewhere in the next days.

@yarrgh Exactly. :)

**Comment by yarrgh** [comment]
After thinking about this a bit more doesn't `TestEnum.One == myEnumVar` already work? 

Unless you're newing up objects outside of the static readonly properties, this should work. By default the framework compares the reference of objects unless explicitly overridden. Since they are pointed to the same instance of the object the equals check would run correctly.

**Comment by ardalis** [comment]
It probably should. Not sure if we have tests that demonstrate this is the case already. If not, we should at least add such tests, so there's no question.

**Comment by DeveTho** [comment]
Hmm, yeah, it should be the same reference. But would it be okay then to just compare by reference, and not the actual value (in case the tests would show it does work)? In that case, it should probably also be documented in the README, as it's a quite implicit thing.

Though I'm probably already thinking ahead a little. I'll try to have a look at it and let you know about and show what I found. :)

**Comment by yarrgh** [comment]
To be safe, it might be best to compare the value.

I'm just remembering that an empty constructor was added to play nice with Entity Framework which, I believe, creates a new instance of the SmartEnum (see #15). In this case comparing by reference would be incorrect.

**Comment by DeveTho** [comment]
Just thought to quickly let you know I haven't further looked into it yet, sorry. But I didn't forget about it!

Also, thanks for the remarks on the EF constructor.

**Comment by DeveTho** [comment]
I just created a pull request #22 that provides this feature, I hope in a good way.

For tests, I only added some that check different instances of the SmartEnum (like when using EF). Checks by reference are already done in other tests, like `SmartEnumExplicitConversion`.

Feel free to let me know if there are other ideas about doing this. :)

**Comment by DeveTho** [comment]
I thought to quickly give a heads-up that if there's something I can do still regarding this issue / feature, feel free to let me know. Otherwise I'll just wait for feedback. :)

**Comment by ardalis** [comment]
What, a month seems like too long for me to look at this? ;)

**Comment by ardalis** [comment]
Merged - I'll try to publish a new build to Nuget soon. Thanks!
