### ISSUE TITLE
Ardalis.SmartEnum.EFCore and Entity Framework Core v6

### ISSUE THREAD

**Issue by BenWhite27** [ardalis/SmartEnum#201]
It appears some API's were changed in EFCore v6 which means we now get a MissingMethodException when calling `ConfigureSmartEnum()`

Specifically this commit seems to be the one that has the changes, https://github.com/dotnet/efcore/commit/9a8c6c750d5166b7ae4423b3ceb05da2bf6561f3#diff-c60aa50a5ed91b1d551a38d9499f85573f144b164f5adf192ef265a368c504f2
Looks like they swapped out some interface definitions for new ones, `ITypeBase` is now `IReadOnlyTypeBase`

I would imagine a version bump in the package dependencies is all that's required to fix it.

```
System.MissingMethodException: Method not found: 'System.Type Microsoft.EntityFrameworkCore.Metadata.ITypeBase.get_ClrType()'.
   at SmartEnum.EFCore.SmartEnumConverterExtensions.ConfigureSmartEnum(ModelBuilder modelBuilder)
   at My.Namespace.Infrastructure.Data.MyDbContext.OnModelCreating(ModelBuilder modelBuilder)
```

**Comment by samuelwine** [comment]
@ardalis is this something I could help with to fix?

**Comment by ardalis** [comment]
Sure, go for it.

**Comment by nagasudhirpulla** [comment]
Hi, I am getting the same error when ConfigureSmartEnum method is executed in a project where I am using dotnet 6 with SmartEnum.EfCore
Please resolve this issue

**Comment by mgraf1** [comment]
@ardalis any chance we could get a new release with these changes? Thanks!
