### ISSUE TITLE
Alternative implementation

### ISSUE THREAD

**Issue by OmiCron07** [ardalis/SmartEnum#24]
I changed the "nameof(One)", from the main page example, by this:

```
  public class MessageTypeEnum : SmartEnum<MessageTypeEnum, int>
  {
    protected MessageTypeEnum(int value, [CallerMemberName] string name = null) : base(name, value)
    {
    }

    public static MessageTypeEnum None { get; } = new MessageTypeEnum(0);

    public static MessageTypeEnum Error { get; } = new MessageTypeEnum(1);

    public static MessageTypeEnum Question { get; } = new MessageTypeEnum(2);

    public static MessageTypeEnum Warning { get; } = new MessageTypeEnum(3);

    public static MessageTypeEnum Information { get; } = new MessageTypeEnum(4);
  }
```

The key here is the attribute CallerMemberName in the constructor fed at compile time.

I did this too:

```
    private static int _i = 0;
    public static MessageTypeEnum None { get; } = new MessageTypeEnum(_i++);
    public static MessageTypeEnum Error { get; } = new MessageTypeEnum(_i++);
```

It works, but I don't know if the values are guaranteed to be always the same, so I'm hesitant to do that. What do you say?

**Comment by ardalis** [comment]
Looking at this now. I like CallerMemberName and don't see a problem with that. The i++ trick should work as well until *you* change the order of your initialization of your enum values. As long as you never do that, it'll be fine. ;)
