### ISSUE TITLE
SmartFlagEnum not available in NuGet package

### ISSUE THREAD

**Issue by zackasattackas** [ardalis/SmartEnum#246]
It doesn't look like the SmartFlagEnum was ever published as part of the Ardalis.SmartEnum nuget package. I have downloaded and decompiled the .dll of each available version, and none of them contain the SmartFlagEnum type.

**Comment by ardalis** [comment]
This should be resolved now with v2.1.0

https://www.nuget.org/packages/Ardalis.SmartEnum/2.1.0
