### ISSUE TITLE
prevent multiple enums with same value ?

### ISSUE THREAD

**Issue by abodehq** [ardalis/SmartEnum#247]
thanks for this great library , 

is there a way to prevent multiple enums with same value. and thru an exception like what regular enum did.

thanks alot.

**Comment by ardalis** [comment]
See #30.

In C# it's valid to have the same value with multiple labels in an enum. So, SmartEnum allows this as well. You would need to have another way to detect this if you want to prevent it, such as a unit test that verified the set of values contained no duplicates.
