### ISSUE TITLE
Equality not useful when instantiated via EF6

### ISSUE THREAD

**Issue by dlumpp** [ardalis/SmartEnum#25]
I'm trying to store just the value of my SmartEnum in a database with EF6 using the technique in your great article [here](https://ardalis.com/persisting-the-type-safe-enum-pattern-with-ef-6). It works fine and I was hoping to be able to use the handy new Equals implementation provided by @DeveTho in #22 on the resulting selected entities.

The trouble is that EF6 doesn't set the Name (only the Value) and Equals is testing both name and value resulting in always-false comparisons. Your EF Core configuration in the readme solves this, but I can't find a way to do a similar type conversion in EF6. 

I can think of three potential solutions:

1. Provide some magical type-converting EF6 configuration that I'm unaware of.
2. Drop the Name equality test from Equals and only test Value. Of course, this would cause problems if you had more than one SmartEnum with the same value but I don't know why you'd want that anyway.
3. Change the Value setter to also set the Name as suggested by commenter Naeem Sarfraz on your article I referenced above.
```C#
private int _value;
public int Value
{
    get { return _value; }
    private set
    {
        Name = FromValue(value).Name;
        _value = value;
    }
}
```

What do you think? Would you accept a PR for any of these?

**Comment by DeveTho** [comment]
Yeah, but on the other hand, you could think Name is actually what should be compared on. As I understand it, that is kind of the "key" of a SmartEnum item.

**Comment by dlumpp** [comment]
I could just compare `.Value`s and call it a day I guess but we're so close to `==` working now in this scenario after this latest release. I don't think what I'm trying to write would work without the new `Equals` behavior either since the references won't be the same.

As you suggested, I tested out a minimal repro to see what would happen using 1.0.3. This trick doesn't work at all with any version before 1.0.5. EF throws saying "Value is not a declared property" because there is no setter. After some searching I found that EF can't create immutable objects - you need at least a private setter. Looked back at your article and noticed you had private setters there. Turns out my addition of a `protected` setter is the only reason it's now possible for EF6 to work like this. Happy accident I guess.

**Comment by DeveTho** [comment]
On a side note: what if someone would map `Name` with EF, or use any other way where only `Name` is compared (instead of `Value`)? Is this a valid scenario, or would this be an unintended use of the SmartEnum?

**Comment by ardalis** [comment]
@DeveTho Do you mean use EF to store the name as a string in the database, rather than the value as a number or guid?

**Comment by DeveTho** [comment]
Yes, exactly. In a way that you would use for example the following mapping configuration:
```c#
modelBuilder.Entity<ApplicationUser>().Property(a => a.Role.Name);
```

I'm not sure if it would make sense, as I guess `Value` should hold the actual data, but I thought to ask to be sure.

**Comment by aalmada** [comment]
How does EF deal with C# with same values?

**Comment by ardalis** [comment]
I think this is resolved; re-open if you need to.
