### ISSUE TITLE
How can we use an empty string value for a SmartEnum

### ISSUE THREAD

**Issue by Tyler-V** [ardalis/SmartEnum#302]
We have several codes that can appear on a file; "V", "R", "S", "Z" or it is empty ""

When we add a smart enum property for "" we are unable to invoke TryFromName without an error

What is the proper way to handle a smart enum for a null or empty string value?

`
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an i
nvocation.
 ---> System.TypeInitializationException: The type initializer for 'CarveOutReason' threw an exception.
 ---> System.ArgumentException: Argument cannot be null or empty. (Parameter 'name')
`

```
using Ardalis.SmartEnum;

foreach (var item in new string[] { "V", "R", "S", "", "Z" })
{
    CarveOutReason.TryFromName(item, out var carveOutReason);
    Console.WriteLine(carveOutReason);
}

public sealed class CarveOutReason : SmartEnum<CarveOutReason>
{
    public string Code { get; set; }

    public static readonly CarveOutReason None = new("", 0);
    public static readonly CarveOutReason PharmacyVoid = new("V", 1);
    public static readonly CarveOutReason EligibilityChange = new("R", 2);
    public static readonly CarveOutReason SlowMover = new("S", 3);

    private CarveOutReason(string code, int value) : base(code, value)
    {
        Code = code;
    }

    public static bool Contains(string carveOutReason)
    {
        return List.Select(e => e.Code).Contains(carveOutReason);
    }
}
```

**Comment by arteny** [comment]
Same issue. Exception is trown if List where value is empty string or null

**Comment by ardalis** [comment]
Hmm, I hadn't considered anyone would want to have an empty SmartEnum, since you can't AFAIK have an empty `enum` type. I don't suppose there's any reason why this couldn't be supported, though.

**Comment by arteny** [comment]
> Hmm, I hadn't considered anyone would want to have an empty SmartEnum, since you can't AFAIK have an empty `enum` type. I don't suppose there's any reason why this couldn't be supported, though.

In my case I am using SmartEnum for fixed string Statuses of some entity. And this statuses has predefined (3rd party) values, one of them is empty (which is something like Success means).

**Comment by MisinformedDNA** [comment]
I could use this as well.

**Comment by MisinformedDNA** [comment]
I'll create a PR.

**Comment by fiseni** [comment]
In the scope of enabling NRT, I'm going through old issues to understand the various requirements of users.
Here, I noticed that @Tyler-V is asking for empty/null `Name` support, not `Value`. In the related PR, we added support for nullable values instead.
