### ISSUE TITLE
Missing extension method ConfigureSmartEnum on ModelConfigurationBuilder in EFCore NuGet

### ISSUE THREAD

**Issue by daniel-fink-de** [ardalis/SmartEnum#306]
I wanted to use a value conversion of smart enums in ef core 6, but it seems that the SmartEnumConverterExtension is missing the extension method on ModelConfigurationBuilder in the EFCor NuGet. I am not sure if this method is still needed since there also is an extension method on the ModelBuilder itself. However, both methods are mentioned in the readme.

**Comment by ardalis** [comment]
I need to get another version published; will try to do so soon.

**Comment by NoCodeMonkey** [comment]
Still an issue. Any chance you can publish another version?

**Comment by ardalis** [comment]
Dang, I thought I'd gotten to this. Guess not... Ok adding it to this week's TODO list.

**Comment by kjbetz** [comment]
I'm running into this... not sure if this is still an issue, or if I'm not configuring it right (or missing a using statement or something.) Any ideas? Thanks!

**Comment by ardalis** [comment]
I released the 7.0 version last month - are you running the latest version and still seeing this behavior?

**Comment by kjbetz** [comment]
Disregard... I had an improper using statement.

The using statement should read: `using SmartEnum.EFCore;`

Thanks!
