### ISSUE TITLE
Localization with SmartEnum

### ISSUE THREAD

**Issue by attiqeurrehman** [ardalis/SmartEnum#38]
Hi Steve,

Thanks for such an amazing smart utility. I was wondering how can we use localization with SmartEnum? With a standard enum, you could add localization custom attribute and get the required information. 

Thanks,
Attiqe

**Comment by ardalis** [comment]
Does this do it?
https://stackoverflow.com/a/1138995/13729

**Comment by attiqeurrehman** [comment]
Yes. Thanks.
