### ISSUE TITLE
Missing nuget packages

### ISSUE THREAD

**Issue by peterbom86** [ardalis/SmartEnum#40]
I've tried to install Ardalis.SmartEnum.AutoFixture, but it seems to be missing?

    PM> Install-Package Ardalis.SmartEnum.AutoFixture
    Install-Package : Unable to find package 'Ardalis.SmartEnum.AutoFixture'
    At line:1 char:1
    + Install-Package Ardalis.SmartEnum.AutoFixture
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId :  NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by ardalis** [comment]
@aalmada Do I need to publish each one of these as separate nuget package, or is there a better way to manage it? 
- AutoFixture
- JsonNet
- MessagePack
- ProtoBufNet
- Utf8Json

I guess I was hoping we could bundle them all as a meta-package or something. Thoughts? Hopefully I won't need to re-publish them with every minor update to SmartEnum. They seem not to require that.

**Comment by attiqeurrehman** [comment]
@ardalis Wouldn't be bundling one package we get more bits than we bargained for? I mean if I am not using ProtoBufNet I don't need bits with respects it?

**Comment by ardalis** [comment]
I get that. It's just more effort on my side to manage several different packages. I need to set some time aside (or have someone PR) to automate it so it's effortless.

**Comment by CumpsD** [comment]
Just got bit by this too, after reading the README I discovered they aren't on nuget.org

**Comment by waynethompson** [comment]
> Just got bit by this too, after reading the README I discovered they aren't on nuget.org
Where does it say that. I have just copied the file to my project for now.
There isn't much to them. I would include in the base nuget package.

**Comment by DunnJM** [comment]
What's the solution for this? I can't seem to install the serialisation package either.

**Comment by danielmeza** [comment]
I can help with, for do that we can reorder the solution and split up in 
* **src/**  
For ship-able code
* **tests/**  
For all the tests projects 
Also I will create a Directory.Build.props to reduce the effort
This way we can simplify the packaging process

**Comment by ardalis** [comment]
@danielmeza sounds good, please send a PR when you have time.

**Comment by danielmeza** [comment]
@ardalis I made the pull request.

**Comment by ankitvijay** [comment]
HI @ardalis, I see that the Pull request raised by @danielmeza for this issue has not been merged.
Here is PR: https://github.com/ardalis/SmartEnum/pull/62
Is there anything I could do to help merge this request? I'm exploring to use SmartEnum in one of our projects and these additional Nuget packages will be of great help.
Thanks!
Ankit

**Comment by danielmeza** [comment]
@ankitvijay the pull request is done! Now we need to include documentation, you can help with that? The next step is to join to .net foundation.

**Comment by ankitvijay** [comment]
Hi, @danielmeza sure, would love to add bits to the documentation. 
`ReadMe.md` appears to be updated already. Can you help me understand where and what else needs to be updated?

**Comment by danielmeza** [comment]
Yes! The missing part are the recently added nugget packages to support Utf8Json, MessagePack etc.

**Comment by ankitvijay** [comment]
Great! and good to see that PR has been merged. Thanks, @danielmeza, and @ardalis :)

**Comment by ardalis** [comment]
These are published now.
https://www.nuget.org/packages?q=Ardalis.SmartEnum
