### ISSUE TITLE
Cannot declare SmartEnum<T, string>

### ISSUE THREAD

**Issue by robertstefan** [ardalis/SmartEnum#42]
Prior to latest release I could declare a SmartEnum as the title says, w/o any errors.

I needed a mapping for some mimetypes, so I created the following enum:

```csharp
public sealed class MimeType : SmartEnum<MimeType, string>
    {
        #region MyRegion

        public static readonly MimeType ai = new MimeType(nameof(ai), "application/postscript");
        public static readonly MimeType aif = new MimeType(nameof(aif), "audio/x-aiff");
        public static readonly MimeType aifc = new MimeType(nameof(aifc), "audio/x-aiff");
        public static readonly MimeType aiff = new MimeType(nameof(aiff), "audio/x-aiff");
        public static readonly MimeType asc = new MimeType(nameof(asc), "text/plain");
        public static readonly MimeType mid = new MimeType(nameof(mid), "audio/midi");
        public static readonly MimeType midi = new MimeType(nameof(midi), "audio/midi");
        public static readonly MimeType mif = new MimeType(nameof(mif), "application/vnd.mif");
        public static readonly MimeType mov = new MimeType(nameof(mov), "video/quicktime");
        public static readonly MimeType movie = new MimeType(nameof(movie), "video/x-sgi-movie");
        public static readonly MimeType mp2 = new MimeType(nameof(mp2), "audio/mpeg");
        public static readonly MimeType mp3 = new MimeType(nameof(mp3), "audio/mpeg");
        public static readonly MimeType mp4 = new MimeType(nameof(mp4), "video/mp4");
        public static readonly MimeType mpe = new MimeType(nameof(mpe), "video/mpeg");
        public static readonly MimeType mpeg = new MimeType(nameof(mpeg), "video/mpeg");
        public static readonly MimeType mpg = new MimeType(nameof(mpg), "video/mpeg");
        public static readonly MimeType mpga = new MimeType(nameof(mpga), "audio/mpeg");
        public static readonly MimeType ra = new MimeType(nameof(ra), "audio/x-pn-realaudio");
       
        #endregion

        private MimeType(string name, string value) : base(name, value)
        {

        }
    }
```

After the package update, I get the error:

Error	CS0453
```The type 'string' must be a non-nullable value type in order to use it as parameter 'TValue' in the generic type or method 'SmartEnum<TEnum, TValue>'```

After searching by the error-code, apparently, there is a known and opened discussion about this issue [here](https://github.com/dotnet/roslyn/issues/9932) ?

**Comment by aalmada** [comment]
I [constrained the value to struct (value types only)](https://github.com/ardalis/SmartEnum/blob/f6278c1af2671f8c934f7190a3d35f10aaf852d2/src/SmartEnum/SmartEnum.cs#L34) so that we don't have to check for `null` everywhere, improving performance. This is fine when using numbers. I questioned myself if people actually used `string`. Looks like they do... 🤔

I'll research into if it's possible to have both implementations. If not, maybe it's a good time for me to learn [C#8 nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/nullable-reference-types).
