### ISSUE TITLE
SmartEnumExtensions.IsSmartEnum returns false if abstract

### ISSUE THREAD

**Issue by ghost** [ardalis/SmartEnum#43]
Calling `SmartEnumExtensions.IsSmartEnum` for a `SmartEnum<>`-derived type returns `false` if the type is `abstract`. Is there a reason this method checks if the type is abstract and returns false? `EmployeeType` and `ReservationStatus` in the examples would return false for `typeof(EmployeeType).IsSmartEnum()` or `typeof(ReservationStatus).IsSmartEnum()` even though they are SmartEnums. 
  
Am I misunderstanding the intended usage of the extension method?

**Comment by aalmada** [comment]
The intent of `IsSmartEnum()` is to know if it's an instanceable `SmartEnum`. This is used in the serializers logic.

Please let me know if I'm assuming this wrong...

**Comment by webwizgordon** [comment]
Ok it sounds like I just misunderstood the intended purpose then. 
  
I needed to know if a property type is a `SmartEnum` type for some special handling in my swagger generation. I just rolled my own extension method instead since the declared property type is not instanceable in my case.

**Comment by ardalis** [comment]
@aalmada is correct; closing now.
