### ISSUE TITLE
Value can not be string?

### ISSUE THREAD

**Issue by djordjedjukic** [ardalis/SmartEnum#46]
It's not possible to set string as value. 
I think it is important to have that possibility.
@ardalis Your thoughts? Is there a plan to support that?
Thank you

**Comment by aalmada** [comment]
Duplicate #42 
It's been fixed by #44 
Waiting for release...

**Comment by ardalis** [comment]
Thanks for the nudge. I was hoping to deal with #40 in the next release but I don't think that's going to happen. I'll get a point release done to support this behavior and then will loop back around to look at other issues next month. Look for a new release tomorrow.

**Comment by DejanMilicic** [comment]
@djordjedjukic I can confirm this issue as being solved in the latest version 1.0.7

**Comment by djordjedjukic** [comment]
Solved, thanks @ardalis
