### ISSUE TITLE
Please Release Version for .NET 8.0

### ISSUE THREAD

**Issue by Elencon** [ardalis/SmartEnum#462]

**Comment by gldraphael** [comment]
Thoughts on the right way to do this? Update the `TargetFramework` to `net8`, or should it support multiple `TargetFrameworks`?

**Comment by gldraphael** [comment]
My thoughts are that this should support .NET 8, .NET 7, and .NET 6, and .NET Standard 2.1. 
(To support .NET Framework and/or UWP, we would need .NET Standard 2.0.)

[Supported .NET versions:](https://dotnet.microsoft.com/en-us/platform/support/policy)

![image](https://github.com/ardalis/SmartEnum/assets/10794213/393cce88-3acf-4085-aee5-797ec229ae25)

[Supported platforms:](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-1#select-net-standard-version)

![image](https://github.com/ardalis/SmartEnum/assets/10794213/c3d991cc-b9e0-4d1e-b4d2-b980a6a24007)



But I see nothing wrong with only supporting .NET 8 and asking users to use an older version if they're on an older version or unsupported platform.

**Comment by ardalis** [comment]
Done!

https://www.nuget.org/packages/Ardalis.SmartEnum/
