### ISSUE TITLE
Derived List call only lists the base class items

### ISSUE THREAD

**Issue by brianbarnett316** [ardalis/SmartEnum#49]
I have a base class and two derived classes (code drastically simplified here).  The base has no enum items but the two derived classes do.

I have a simple console app to test listing the enums.  However, I the List property is not returning any items on the derived classes.  Is this an issue or am I using this wrong?  The intent is to have a base Error enum type that other services would derive from.  Each service would have their own list of errors but I would like them to all be derived from the base Error type.

If I add enum items to the base Error class those items are listed multiple times.

    public class Error : SmartEnum<Error>
    {
        protected Error(string name, int value) : base(name, value)
        {
        }
        //Will have other properties here...
    }

    public class DerivedError1 : Error
    {
        public static DerivedError1 Error1Four = new DerivedError1("Derived 1-1", 0);
        public static DerivedError1 Error1Five = new DerivedError1("Derived 1-2", 1);
        public static DerivedError1 Error1Six = new DerivedError1("Derived 1-3", 2);

        private DerivedError1(string name, int value) : base(name, value)
        {
        }
    }

    public class DerivedError2 : Error
    {
        public static DerivedError2 ErrorFour = new DerivedError2("Derived 2-1", 0);
        public static DerivedError2 ErrorFive = new DerivedError2("Derived 2-2", 1);
        public static DerivedError2 ErrorSix = new DerivedError2("Derived 2-3", 2);

        private DerivedError2(string name, int value) : base(name, value)
        {
        }
    }

    class Program
    {
        static void Main(string[] args)
        {

            //Nothing expected here
            foreach (var baseError in Error.List)
            {
                Console.WriteLine($"{baseError.Value} - {baseError.Name}");
            }

           //Expected to see 3 items here, get zero.
            foreach (var derivedError in DerivedError1.List)
            {
                Console.WriteLine($"{derivedError.Value} - {derivedError.Name}");
            }

           //Expected to see 3 items here, get zero.
            foreach (var derivedError in DerivedError2.List)
            {
                Console.WriteLine($"{derivedError.Value} - {derivedError.Name}");
            }

            Console.ReadLine();
        }
    }

I'm seeing a similar issue with TestEnum.cs from the SmartEnum.UnitTests project if I add a second enum to the TestDerivedEnum class.

    public abstract class TestBaseEnum : SmartEnum<TestBaseEnum>
    {
        public static TestBaseEnum One;

        internal TestBaseEnum(string name, int value) : base(name, value)
        {
        }
    }

    public sealed class TestDerivedEnum : TestBaseEnum
    {
        public static TestBaseEnum Two;

        private TestDerivedEnum(string name, int value) : base(name, value)
        {
        }

        static TestDerivedEnum()
        {
            One = new TestDerivedEnum(nameof(One), 1);
            Two = new TestDerivedEnum(nameof(Two), 2);
        }

        public static new TestBaseEnum FromValue(int value) =>
            TestBaseEnum.FromValue(value);

        public static new TestBaseEnum FromName(string name, bool ignoreCase = false) =>
            TestBaseEnum.FromName(name, ignoreCase);
    }

Also, FromValue doesn't find enum 2.
var result2 = TestDerivedEnum.FromValue(2);

Thanks,
Brian

**Comment by ardalis** [comment]
Fixed and published.
https://www.nuget.org/packages/Ardalis.SmartEnum/1.0.8
(currently verifying - available soon)

**Comment by sdepouw** [comment]
Hi Brian,
We just merged in a change that should resolve this issue. Now when you call `Error.List` and it will contain all the items from `DerivedError1` and `DerivedError2`.

If you call `DerivedError1.List` it will also return every enum value. If you need your derived types' `List` to just return its own items, you can override the List property in your derived enum like so:

    public class DerivedTestEnumWithValues1 : TestBaseEnumWithDerivedValues
    {
        public new static IReadOnlyCollection<DerivedTestEnumWithValues1> List
        {
            get
            {
                return TestBaseEnumWithDerivedValues.List.Where(val => val is DerivedTestEnumWithValues1).Cast<DerivedTestEnumWithValues1>().ToList();
            }
        }
    }

This allows you to call `DerivedTestEnumWithValues1.List` and get just the enum values whose type is `DerivedTestEnumWithValues1`.

Hope this helps!

**Comment by brianbarnett316** [comment]
Steve and Scott,

Thanks so much for the quick response.  Your changes worked perfectly!

I'm just beginning to play with SmartEnum but so far looks like an incredibly handy library.

Thanks,
Brian

**Comment by richardaubin** [comment]
I just encountered the same issue of the derived class list containing values from all derived classes.

I'm sorry but this is very unintuitive to have to override the list to provide only the values of the derived class.  Is there no other way you can manage this to prevent another derived classes items from showing in another's list?

**Comment by ardalis** [comment]
It doesn't look like we can make everyone happy with the default behavior, since some folks want all options shown and others do not. Given that there is a relatively straightforward workaround shown above I don't think we will introduce a breaking change to reverse the default behavior at this time.
