### ISSUE TITLE
Add a way to enumerate over the List to prevent allocation every time List is called

### ISSUE THREAD

**Issue by akarboush** [ardalis/SmartEnum#494]
Introduce a way to enumerate the enum values without unnecessary memory allocation. This will be useful especially for scenarios requiring frequent iteration. 

I'd happily do a PR if that's okay. 
Something like this:

```cs
public static IEnumerable<TEnum> EnumerateList() => _fromName.Value.Values;
````

**Comment by ardalis** [comment]
Yeah, that would be a great addition. PR away!
