### ISSUE TITLE
eliminate explicit dependency for STJ on newer frameworks

### ISSUE THREAD

**Issue by thompson-tomo** [ardalis/SmartEnum#515]
**Is your feature request related to a problem? Please describe.**
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

**Describe the solution you'd like**
I want the package to have conditions placed on System.Text.Json so that it can be provided by the framework. Same thing for System.ComponentModel.Annotations

**Describe alternatives you've considered**
Accept the additional dependency

**Additional context**
n/a

**Comment by ardalis** [comment]
What additional TFM are you looking for? What, specifically, needs to change to fix this issue?

**Comment by thompson-tomo** [comment]
@ardalis Will submit a pr which will probs be the easiest way to describe it

**Comment by fiseni** [comment]
Related to dependencies, we should consider [this](https://github.com/ardalis/SmartEnum/pull/463#issuecomment-2039411450) as well.
Perhaps as part of another PR, we need to clean and consolidate them.

**Comment by thompson-tomo** [comment]
@fiseni I have adjusted the condition as suggested and even enabled global package reference for sonar & sourcelink. This meant i needed to add suppressions in.

**Comment by fiseni** [comment]
Why we're suppressing all these messages? These are all valid suggestions. Example

```
[SuppressMessage("Minor Code Smell", "S6602:\"Find\" method should be used instead of the \"FirstOrDefault\" extension", Justification = "<Pending>")]
```

**Comment by fiseni** [comment]
Now I remember we're treating warnings as errors, right? Ok then, great. We'll tackle all those code smells in the future.

**Comment by thompson-tomo** [comment]
Correct warnings are being treated as errors & the projects which got suppressions previously didn't have analysis enabled hence the suppression.
