### ISSUE TITLE
Would it be possible to support netstandard2.0 instead of netstandard2.1?

### ISSUE THREAD

**Issue by ThumNet** [ardalis/SmartEnum#530]
Is there a reason for needing netstandard2.1 which is [not compatible with .Net Framework](https://dotnet.microsoft.com/en-us/platform/dotnet-standard#versions)?

Currently we are stuck at version `2.1.0` of `SmartEnum` and I'd really like to upgrade to the latest version of SmartEnum.
This is not possible due to version `8.0.0` of `SmartEnum` is only supporting `netstandard2.1` instead of `netstandard2.0`, some of our old projects that are still using `net481` (fat framework). We also have the new `net8.0` projects and we share code between them in a `netstandard2.0` library (here the `SmartEnums` live).

I already cloned the repo locally and made a limited amount of changes locally to support `netstandard2.0`, so adding back support should be possible! 

Is this something you are interested in? ~~If so, i'll open up a PR.~~

See #531 for changes required.

**Comment by ardalis** [comment]
Done in 8.1! Sorry for the delay.
