### ISSUE TITLE
When methods do not appear in latest Nuget package

### ISSUE THREAD

**Issue by devonbuckingham** [ardalis/SmartEnum#65]
When referencing the Nuget package in .NET Framework 4.7.2 and .NET Core 3.1, the When methods of SmartEnum are not available. If I build from the repo and reference the dll directly, they are there.

**Comment by ardalis** [comment]
Hmm, it’s possible I need to publish an update. Haven’t put a lot of time into this lately. Let me see if I can push an updated version next week.

**Comment by ardalis** [comment]
Should be fixed now with version 1.0.10
