### ISSUE TITLE
missing nuget packages

### ISSUE THREAD

**Issue by ghendo** [ardalis/SmartEnum#69]
Install-Package Ardalis.SmartEnum.JsonNet
Install-Package Ardalis.SmartEnum.Utf8Json

are missing

**Comment by Gimly** [comment]
All the packages for serialization are missing from Nuget

**Comment by ardalis** [comment]
Yeah, it's been on my TODO list for a while to get these published, ideally with an automatic GitHub action.

**Comment by ardalis** [comment]
These are all listed now.
https://www.nuget.org/packages?q=Ardalis.SmartEnum
