### ISSUE TITLE
MVC Dropdownlists and ViewModels

### ISSUE THREAD

**Issue by Jvella94** [ardalis/SmartEnum#70]
Hi All,

How would you use these in a view model to create a dropdown list for the possible choices in the enum?

Eg: If you take the readme example you would generate a dropdownlist of 

- One
- Two
- Three

which would bind to a viewmodel you then map back to your domain with the smart enum.

**Comment by ardalis** [comment]
If I have time I'll try and whip up a sample showing how to do this, but if someone else wants to send a PR in the meantime that would be great.

**Comment by mistrykam** [comment]
I tried updating the SmartEnum so that it could bind in a Post request in a Razor page.  Haven't been able to come up a solution.  The model binder doesn't want to map the value to the SmartEnum.  Even tried adding implicit operators which didn't work.  

A possible solution would be to create a custom Model Binder: 
https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-5.0

**Comment by nagasudhirpulla** [comment]
I am unable to bind a SmartEnum to razor page dropdown list.
If any one knows any work around, kindly post here.

**Comment by mistrykam** [comment]
Take a look at this example:

Enum definition - or use a Smart Enum:
https://github.com/mistrykam/Dotnet-Clean-Architecture/blob/master/App.Domain.Entities/Enum/BookFormatType.cs

UI Model Binder:
https://github.com/mistrykam/Dotnet-Clean-Architecture/blob/master/App.Client.WebUI/Framework/BookFormatTypeBinder.cs

Example Usage:
https://github.com/mistrykam/Dotnet-Clean-Architecture/blob/master/App.Client.WebUI/Pages/Books/Create.cshtml.cs

**Comment by nagasudhirpulla** [comment]
https://www.c-sharpcorner.com/article/custom-model-binding-in-asp-net-core-mvc/

This article shows how to create custom model binders and inject them in the startup addmvc function.

Based on something like this, we can create a library that scans all smart enums from the user specified solution or project, create model binders and inject them for usage in the razor pages.

Since I am not so good at writing libraries, I am sharing this idea so that interested people can create the solution for smartenum model binding.
I will also try to solve this from my side.

Thanks
Nagasudhir

**Comment by nagasudhirpulla** [comment]
> Take a look at this example:
> 
> Enum definition - or use a Smart Enum: https://github.com/mistrykam/Dotnet-Clean-Architecture/blob/master/App.Domain.Entities/Enum/BookFormatType.cs
> 
> UI Model Binder: https://github.com/mistrykam/Dotnet-Clean-Architecture/blob/master/App.Client.WebUI/Framework/BookFormatTypeBinder.cs
> 
> Example Usage: https://github.com/mistrykam/Dotnet-Clean-Architecture/blob/master/App.Client.WebUI/Pages/Books/Create.cshtml.cs

You should also mention the code where you have registered the model binder - https://github.com/mistrykam/Dotnet-Clean-Architecture/blob/42899a385d9afbe7c5584ab595e45ae3f6969767/App.Client.WebUI/Startup.cs#L37

👆 It took me a lot of time to search this 😂
Anyways thanks for sharing 👍

**Comment by nagasudhirpulla** [comment]
> https://www.c-sharpcorner.com/article/custom-model-binding-in-asp-net-core-mvc/
> 
> This article shows how to create custom model binders and inject them in the startup addmvc function.
> 
> Based on something like this, we can create a library that scans all smart enums from the user specified solution or project, create model binders and inject them for usage in the razor pages.
> 
> Since I am not so good at writing libraries, I am sharing this idea so that interested people can create the solution for smartenum model binding. I will also try to solve this from my side.
> 
> Thanks Nagasudhir

As a continuation, this medium post shows a very good example of how to use IModelBinder for binding all child class types by creating binder for  parent interface. 
https://tomchizek.medium.com/using-net-core-custom-model-binding-eb4b23b35c43
In the same way we can create binder for SmartEnum type.

Thanks
Nagasudhir

**Comment by nagasudhirpulla** [comment]
> Take a look at this example:
> 
> Enum definition - or use a Smart Enum: https://github.com/mistrykam/Dotnet-Clean-Architecture/blob/master/App.Domain.Entities/Enum/BookFormatType.cs
> 
> UI Model Binder: https://github.com/mistrykam/Dotnet-Clean-Architecture/blob/master/App.Client.WebUI/Framework/BookFormatTypeBinder.cs
> 
> Example Usage: https://github.com/mistrykam/Dotnet-Clean-Architecture/blob/master/App.Client.WebUI/Pages/Books/Create.cshtml.cs

Hi this solution looks really nice, but this doesn't generalise. We need to create binder for each smartenum type.

https://stackoverflow.com/a/2380483
👆Using a dynamic converter shown in the above link, you can try to modify your binder to generalize for all smartenums.

I will also try from my side.

Thanks
Nagasudhir

**Comment by nagasudhirpulla** [comment]
> If I have time I'll try and whip up a sample showing how to do this, but if someone else wants to send a PR in the meantime that would be great.

Hi @ardalis
I have created a ModelBinder and ModelBinderProvider for SmartEnum to solve this issue.

The working project is available here - https://github.com/nagasudhirpulla/SmartEnumModelBinding. You can clone the repo and checkout the functionality.

Please read the [readme](https://github.com/nagasudhirpulla/SmartEnumModelBinding/blob/main/README.md) of my repository to understand how it works.

Hope this helps.
BTW, SmartEnum is a great library

Thanks
Nagasudhir

**Comment by nagasudhirpulla** [comment]
Hi @ardalis , even though this issue is resolved, we are unable to use this model binding feature since it is not published as a nuget package. 
Please create a nuget package (new or modify any existing) so that people can use the model binding feature of smartenums in their razor pages from the commit https://github.com/ardalis/SmartEnum/commit/ab7d6a00b950070705bec6d70378706905fd59b9

**Comment by devsbryan** [comment]
Fantastic library, thanks very much. Just encountered this issue and can see its now been solved but not published yet.

@ardalis - Would it be possible to have a new version of the nuget package published that includes this change?

Thanks

**Comment by ardalis** [comment]
Working on this now

**Comment by davidliang2008** [comment]
Hi @ardalis, I saw the model binding package https://github.com/ardalis/SmartEnum/tree/main/src/SmartEnum.ModelBinding. Thank you!

Any plan to make it be compatible with .NET 6 and below? This ModelBinding package depends on SmartEnum (>=7.0.0), but I have to use (2.1.0) for .NET 6.

**Comment by ardalis** [comment]
I'll see what I can do

**Comment by davidliang2008** [comment]
> Hi @ardalis, I saw the model binding package https://github.com/ardalis/SmartEnum/tree/main/src/SmartEnum.ModelBinding. Thank you!
> 
> Any plan to make it be compatible with .NET 6 and below? This ModelBinding package depends on SmartEnum (>=7.0.0), but I have to use (2.1.0) for .NET 6.
> 
> By the way, I copied its source code and put it in a .NET 6 project, and it worked fine. I guess the depedency of SmartEnum (>=7.0.0) might be removed?

Also @ardalis , I see this model binder assumes the value is coming from smartenum's name. I often use smartenum's value instead in forms. Can we cover "FromValue" case as well in the model binder?

Thanks!
