### ISSUE TITLE
Why multiple enums with same value are allowed?

### ISSUE THREAD

**Issue by norvegec** [ardalis/SmartEnum#99]
https://github.com/ardalis/SmartEnum/blob/718b30811b16ffb3f1c6cffe0d6c3d39cb90b6b3/src/SmartEnum/SmartEnum.cs#L46

`SmartEnum` implements `IEquatable<T>` and  `IComparable<T>` based on `Value` rather than `Name`.
So it's not clear to me why this was allowed. Could you please clarify?

**Comment by ardalis** [comment]
Hmm, that's a good question. I honestly don't know why we were (are) supporting duplicate enums with the same value. I assume this is causing you a problem?

**Comment by norvegec** [comment]
Looking at git blame - this behavior has been introduced with performance improvements related to case sensitive/insensitive comparison enum by name.
Moreover, there are tests that assumes this behavior.
It would be nice if you could have a look at [this related comment](https://github.com/ardalis/SmartEnum/pull/100#discussion_r533006400)

**Comment by norvegec** [comment]
I suppose, this is made so that SmartEnum is fully compatible with "standard" enums, which can have same value for different items.
But it looks more like a bug in initial implementation of enums. When MS realized that, they presented [a "fix"](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1069) for this (don't laugh).

So the question is - since `SmartEnum` treats `Name` just as equal as `Value`, should it copy original enums behavior or past it by? Should they both uniquely identifies the entity of SmartEnum?

**Comment by hanslai** [comment]
Currently we add out own validation to make sure both value or name cannot have duplicate value.  It will be nice if SmartEnum handle this natively.  Just throw a descriptive exception will be good enough, I think.

**Comment by abodehq** [comment]
> Currently we add out own validation to make sure both value or name cannot have duplicate value. It will be nice if SmartEnum handle this natively. Just throw a descriptive exception will be good enough, I think.

Can u please share with us the code for this validation we really urgently need it.

**Comment by ardalis** [comment]
See #30. Currently we're using the same behavior as `enum` in C#. Since SmartEnums are typically fully defined at compile time, a simple unit test should be able to verify that there are no duplicate values in a given SmartEnum.

Would a static helper method like `AssertNoDuplicateValues()` be useful?
